In [1]:
import math

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
pip install StatsModels

SyntaxError: invalid syntax (<ipython-input-2-8fdc42802379>, line 1)

In [3]:
!pip install StatsModels

In [4]:
a=[6,7,8,0,1]
print type(a),a

<type 'list'> [6, 7, 8, 0, 1]


In [5]:
b=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(b)
print type(arr2)
arr2

<type 'numpy.ndarray'>


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr2.ndim

2

In [1]:
from __future__ import division
br='\n'

In [2]:
!pip install numpy

In [3]:
from statsmodels.tsa.statools import adfuller as ADF
import numpy as np
ADF(np.random.rand(100))

ImportError: No module named statools

In [4]:
from statsmodels.tsa.stattools import adfuller as ADF
import numpy as np
ADF(np.random.rand(100))

(-8.9407545597058977,
 9.2675345241396408e-15,
 0L,
 99L,
 {'1%': -3.4981980821890981,
  '10%': -2.5825959973472097,
  '5%': -2.8912082118604681},
 47.293777572632962)

In [5]:
arr=np.arange(10)
print arr
print arr[5]
print arr[5:8]

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]


In [6]:
arr_slice=arr[5:8]
arr[1]=12345
print arr
arr_slice[:]=64
print arr

[    0 12345     2     3     4     5     6     7     8     9]
[    0 12345     2     3     4    64    64    64     8     9]


In [7]:
arr2d=[[1,2,3],[4,5,6]]


In [8]:
print arr2d

[[1, 2, 3], [4, 5, 6]]


In [9]:
print arr2d[1]

[4, 5, 6]


In [10]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print arr2d[2]

[7 8 9]


In [11]:
print arr2d[0][2]
print arr2d[0:2]

3
[[1 2 3]
 [4 5 6]]


In [12]:
print arr2d[0,2]

3


In [13]:
old_values=arr2d[0].copy()

In [14]:
print old_values

[1 2 3]


In [15]:
old_values[0]=0
print old_values,arr2d

[0 2 3] [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print arr2d

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
arr=np.random.randn(5,4)
print arr,br

[[ 0.68319641 -1.02657867  0.49312015  0.80294744]
 [-0.25596157  0.44276401 -1.84027009  0.40370375]
 [ 0.65184118 -0.57247242 -1.77158937 -0.16256941]
 [-0.28228512  0.9110847  -0.46350339 -0.14269839]
 [-0.87595854 -0.54861138  0.40859986  0.46114052]] 



In [18]:
print arr.mean(),br

-0.134205016166 



In [19]:
print np.mean(arr),br

-0.134205016166 



In [20]:
print arr.sum(),np.sum(arr),br

-2.68410032331 -2.68410032331 



In [21]:
print arr.std(),np.std(arr),br

0.786442636915 0.786442636915 



In [22]:
print arr[0],br
print arr[:,0],br
print arr.sum(0),br
print arr.mean(axis=0),br
print arr.sum(1),br

[ 0.68319641 -1.02657867  0.49312015  0.80294744] 

[ 0.68319641 -0.25596157  0.65184118 -0.28228512 -0.87595854] 

[-0.07916764 -0.79381376 -3.17364284  1.36252391] 

[-0.01583353 -0.15876275 -0.63472857  0.27250478] 

[ 0.95268532 -1.2497639  -1.85479001  0.0225978  -0.55482953] 



In [23]:
a=np.array([[0,1,2],[3,4,5],[6,7,8]])
print a
print a*a

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [24]:
import scipy
from scipy import linulg

ImportError: cannot import name linulg

In [25]:
import scipy
from scipy import linalg

In [26]:
scipy.mat(a)*scipy.mat(a)

matrix([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

In [27]:
ma=scipy.mat(a)
print type(ma)
print ma

<class 'numpy.matrixlib.defmatrix.matrix'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
ma=scipy.mat(a)*scipy.mat(a)
mb=linalg.inv(ma)
print mb

[[ -1.67609695e+14   3.35219390e+14  -1.67609695e+14]
 [  3.35219390e+14  -6.70438779e+14   3.35219390e+14]
 [ -1.67609695e+14   3.35219390e+14  -1.67609695e+14]]


In [29]:
ma * mb

matrix([[ 1.71875, -1.5625 ,  0.0625 ],
        [ 0.6875 , -4.625  ,  0.625  ],
        [-0.84375, -2.6875 ,  2.6875 ]])

In [30]:
linalg.det(ma)

0.0

In [31]:
x=np.linspace(0,10,1000)
y=np.sin(x)+1
z=np.cos(x**2)+1

In [32]:
plt.figure(figsize=(8,4))
plt.plot(x,y)

NameError: name 'plt' is not defined

In [33]:
import matplotlib.pyplot as plt

In [34]:
x=np.linspace(0,10,1000)
y=np.sin(x)+1
z=np.cos(x**2)+1

In [35]:
plt.figure(figsize=(8,4))
plt.plot(x,y)

In [36]:
plt.figure(figsize=(8,4))
plt.plot(x,y,lanel='$\sin s+1$',color='red',linewidth=2)

AttributeError: Unknown property lanel

In [37]:
plt.figure(figsize=(8,4))
plt.plot(x,y,label='$\sin s+1$',color='red',linewidth=2)