In [1]:
from __future__ import division
import os,sys

%matplotlib inline
import matplotlib.pyplot as plt

import pandas as pd
import numpy as np

In [2]:
datafile='data/air_data.csv'
resultfile='data/explore.xls'

data=pd.read_csv(datafile,encoding='utf-8')
data.head()

MEMBER_NO    FFP_DATE FIRST_FLIGHT_DATE GENDER  FFP_TIER    WORK_CITY  \
0      54993  2006/11/02        2008/12/24      男         6            .   
1      28065  2007/02/19        2007/08/03      男         6          NaN   
2      55106  2007/02/01        2007/08/30      男         6            .   
3      21189  2008/08/22        2008/08/23      男         5  Los Angeles   
4      39546  2009/04/10        2009/04/15      男         6           贵阳   

  WORK_PROVINCE WORK_COUNTRY   AGE   LOAD_TIME       ...         \
0            北京           CN  31.0  2014/03/31       ...          
1            北京           CN  42.0  2014/03/31       ...          
2            北京           CN  40.0  2014/03/31       ...          
3            CA           US  64.0  2014/03/31       ...          
4            贵州           CN  48.0  2014/03/31       ...          

   ADD_Point_SUM  Eli_Add_Point_Sum  L1Y_ELi_Add_Points  Points_Sum  \
0          39992             114452              111100      619760   
1          12000              53288               53288      415768   
2          15491              55202               51711      406361   
3              0              34890               34890      372204   
4          22704              64969               64969      338813   

   L1Y_Points_Sum  Ration_L1Y_Flight_Count  Ration_P1Y_Flight_Count  \
0          370211                 0.509524                 0.490476   
1          238410                 0.514286                 0.485714   
2          233798                 0.518519                 0.481481   
3          186100                 0.434783                 0.565217   
4          210365                 0.532895                 0.467105   

   Ration_P1Y_BPS Ration_L1Y_BPS  Point_NotFlight  
0        0.487221       0.512777               50  
1        0.489289       0.510708               33  
2        0.481467       0.518530               26  
3        0.551722       0.448275               12  
4        0.469054       0.530943               39  

[5 rows x 44 columns]

In [5]:
explore=data.describe(percentiles=[0.25,0.75],include='all').T
explore.head()

count unique         top   freq     mean       std  min  \
MEMBER_NO          62988    NaN         NaN    NaN  31494.5   18183.2    1   
FFP_DATE           62988   3068  2011/01/13    184      NaN       NaN  NaN   
FIRST_FLIGHT_DATE  62988   3406  2013/02/16     96      NaN       NaN  NaN   
GENDER             62985      2           男  48134      NaN       NaN  NaN   
FFP_TIER           62988    NaN         NaN    NaN  4.10216  0.373856    4   

                       25%      50%      75%    max  
MEMBER_NO          15747.8  31494.5  47241.2  62988  
FFP_DATE               NaN      NaN      NaN    NaN  
FIRST_FLIGHT_DATE      NaN      NaN      NaN    NaN  
GENDER                 NaN      NaN      NaN    NaN  
FFP_TIER                 4        4        4      6

In [6]:
explore['null']=len(data)-explore[:]['count']
explore['null'].head()

MEMBER_NO            0
FFP_DATE             0
FIRST_FLIGHT_DATE    0
GENDER               3
FFP_TIER             0
Name: null, dtype: object

In [9]:
explore=explore[['null','max','min']]
explore.columns=[u'空值数',u'最大值',u'最小值']

explore.head()

空值数    最大值  最小值
MEMBER_NO           0  62988    1
FFP_DATE            0    NaN  NaN
FIRST_FLIGHT_DATE   0    NaN  NaN
GENDER              3    NaN  NaN
FFP_TIER            0      6    4

In [10]:
explore.to_excel(resultfile)

In [11]:
print explore.ix['SUM_YR_1']
print explore.ix['SUM_YR_2']

空值数       551
最大值    239560
最小值         0
Name: SUM_YR_1, dtype: object
空值数       138
最大值    234188
最小值         0
Name: SUM_YR_2, dtype: object


In [12]:
print explore.ix['avg_discount']

空值数      0
最大值    1.5
最小值      0
Name: avg_discount, dtype: object


In [14]:
print explore.ix['SEG_KM_SUM']

空值数         0
最大值    580717
最小值       368
Name: SEG_KM_SUM, dtype: object


In [15]:
datafile='data/air_data.csv'
cleanedfile='data/air_data_cleaned.csv'

In [16]:
data=pd.read_csv(datafile,encoding='utf-8')
print u'原始数据条数：',len(data)

原始数据条数： 62988


In [20]:
index1=data['SUM_YR_1']!=0
index2=data['SUM_YR_2']!=0
index3=(data['SEG_KM_SUM']==0)&(data['avg_discount']==0)
data=data[index1|index2|index3]

data.to_csv(cleanedfile,encoding='utf-8')
print u'清洗后数据条数：',len(data)

清洗后数据条数： 62733


In [21]:
data.head()

MEMBER_NO    FFP_DATE FIRST_FLIGHT_DATE GENDER  FFP_TIER    WORK_CITY  \
0      54993  2006/11/02        2008/12/24      男         6            .   
1      28065  2007/02/19        2007/08/03      男         6          NaN   
2      55106  2007/02/01        2007/08/30      男         6            .   
3      21189  2008/08/22        2008/08/23      男         5  Los Angeles   
4      39546  2009/04/10        2009/04/15      男         6           贵阳   

  WORK_PROVINCE WORK_COUNTRY   AGE   LOAD_TIME       ...         \
0            北京           CN  31.0  2014/03/31       ...          
1            北京           CN  42.0  2014/03/31       ...          
2            北京           CN  40.0  2014/03/31       ...          
3            CA           US  64.0  2014/03/31       ...          
4            贵州           CN  48.0  2014/03/31       ...          

   ADD_Point_SUM  Eli_Add_Point_Sum  L1Y_ELi_Add_Points  Points_Sum  \
0          39992             114452              111100      619760   
1          12000              53288               53288      415768   
2          15491              55202               51711      406361   
3              0              34890               34890      372204   
4          22704              64969               64969      338813   

   L1Y_Points_Sum  Ration_L1Y_Flight_Count  Ration_P1Y_Flight_Count  \
0          370211                 0.509524                 0.490476   
1          238410                 0.514286                 0.485714   
2          233798                 0.518519                 0.481481   
3          186100                 0.434783                 0.565217   
4          210365                 0.532895                 0.467105   

   Ration_P1Y_BPS Ration_L1Y_BPS  Point_NotFlight  
0        0.487221       0.512777               50  
1        0.489289       0.510708               33  
2        0.481467       0.518530               26  
3        0.551722       0.448275               12  
4        0.469054       0.530943               39  

[5 rows x 44 columns]

In [22]:
datafile='data/air_data.csv'
cleanedfile='data/air_data_cleaned.csv'

data=pd.read_csv(datafile,encoding='utf-8')
print u'原始数据条数',len(data)

原始数据条数 62988


In [23]:
index1=data['SUM_YR_1']!=0
index2=data['SUM_YR_2']!=0
index3=(data['SEG_KM_SUM']==0)&(data['avg_discount']==0)
data=data[index1|index2|index3]

data=data[['FFP_DATE','LAST_TO_END','FLIGHT_COUNT','SEG_KM_SUM','LOAD_TIME','avg_discount']]

data.to_csv(cleanedfile,encoding='utf-8',index=False)
print u'清洗后数据条数：',len(data)
data.head()

清洗后数据条数： 62733


FFP_DATE  LAST_TO_END  FLIGHT_COUNT  SEG_KM_SUM   LOAD_TIME  avg_discount
0  2006/11/02            1           210      580717  2014/03/31      0.961639
1  2007/02/19            7           140      293678  2014/03/31      1.252314
2  2007/02/01           11           135      283712  2014/03/31      1.254676
3  2008/08/22           97            23      281336  2014/03/31      1.090870
4  2009/04/10            5           152      309928  2014/03/31      0.970658

In [25]:
datafile='data/air_data_cleaned.csv'
normdfile='data/air_data_normd.csv'

data=pd.read_csv(datafile,encoding='utf-8')

data[u'LOAD_TIME']=pd.to_datetime(data[u'LOAD_TIME'])
data[u'FFP_DATE']=pd.to_datetime(data[u'FFP_DATE'])

data['L']=(data[u'LOAD_TIME']-data[u'FFP_DATE'])/np.timedelta64(1,'M')
data['R']=data['LAST_TO_END']
data['F']=data['FLIGHT_COUNT']
data['M']=data['SEG_KM_SUM']
data['C']=data['avg_discount']

data=data[['L','R','F','M','C']]

data=(data-data.mean(axis=0))/(data.std(axis=0))

data.columns=['Z'+i for i in data.columns]
data.to_csv(normdfile,encoding='utf-8',index=False)
data.head()

ZL        ZR         ZF         ZM        ZC
0  1.439535 -0.950023  14.083484  26.849457  1.294406
1  1.310895 -0.917429   9.107769  13.173891  2.863645
2  1.332139 -0.895700   8.752360  12.699075  2.876392
3  0.661794 -0.428515   0.791215  12.585874  1.992070
4  0.389171 -0.928294   9.960749  13.948099  1.343095

In [26]:
from sklearn.cluster import KMeans

inputfile='data/air_data_normd.csv'
k=5

data=pd.read_csv(inputfile)

kmodel=KMeans(n_clusters=k,n_jobs=8)
kmodel.fit(data)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=5, n_init=10, n_jobs=8, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [27]:
kmodel.cluster_centers_

array([[ 0.02364658,  0.02129491, -0.25245177, -0.26095747,  2.06570684],
       [-0.3213966 ,  1.67377631, -0.57457135, -0.53738533, -0.19669685],
       [ 1.16824642, -0.38215137, -0.08188688, -0.08946555, -0.16070345],
       [-0.69787422, -0.42593922, -0.15353758, -0.15290762, -0.26480705],
       [ 0.48761871, -0.80631809,  2.49519621,  2.43624143,  0.31474566]])

In [29]:
kmodel.labels_

array([4, 4, 4, ..., 1, 1, 1])

In [30]:
data['Class']=kmodel.labels_
data.head()

ZL        ZR         ZF         ZM        ZC  Class
0  1.439535 -0.950023  14.083484  26.849457  1.294406      4
1  1.310895 -0.917429   9.107769  13.173891  2.863645      4
2  1.332139 -0.895700   8.752360  12.699075  2.876392      4
3  0.661794 -0.428515   0.791215  12.585874  1.992070      4
4  0.389171 -0.928294   9.960749  13.948099  1.343095      4

In [31]:
data.groupby(['Class']).count()

ZL     ZR     ZF     ZM     ZC
Class                                   
0       4712   4712   4712   4712   4712
1      12363  12363  12363  12363  12363
2      15746  15746  15746  15746  15746
3      24560  24560  24560  24560  24560
4       5352   5352   5352   5352   5352

In [32]:
m=data.groupby(['Class']).mean()
c=data.groupby(['Class']).count()
m[u'聚类个数']=c['ZL']
m

ZL        ZR        ZF        ZM        ZC   聚类个数
Class                                                         
0      0.023160  0.019621 -0.252140 -0.260359  2.070345   4712
1     -0.321403  1.673645 -0.574457 -0.537332 -0.196198  12363
2      1.168139 -0.381871 -0.081975 -0.089649 -0.159999  15746
3     -0.697837 -0.425707 -0.153641 -0.152985 -0.264456  24560
4      0.487619 -0.806318  2.495196  2.436241  0.314746   5352

In [33]:
kmodel.cluster_centers_[0]

array([ 0.02364658,  0.02129491, -0.25245177, -0.26095747,  2.06570684])

In [34]:
data.groupby(['Class']).describe()

ZC            ZF            ZL            ZM  \
Class                                                                 
0     count   4712.000000   4712.000000   4712.000000   4712.000000   
      mean       2.070345     -0.252140      0.023160     -0.260359   
      std        1.041939      0.528421      0.919596      0.541705   
      min        0.628718     -0.701499     -1.323277     -0.800448   
      25%        1.226637     -0.630418     -0.764460     -0.638281   
      50%        1.606733     -0.488254     -0.098245     -0.460702   
      75%        2.920202     -0.061764      0.721983     -0.073288   
      max        4.200799      2.568257      2.302250      2.759719   
1     count  12363.000000  12363.000000  12363.000000  12363.000000   
      mean      -0.196198     -0.574457     -0.321403     -0.537332   
      std        0.925698      0.194583      0.810080      0.244132   
      min       -3.897093     -0.701499     -1.323277     -0.800448   
      25%       -0.828480     -0.701499     -0.970402     -0.687056   
      50%       -0.118077     -0.630418     -0.573860     -0.614638   
      75%        0.432634     -0.559336      0.161395     -0.479116   
      max        2.581221      1.715277      2.302250      2.677629   
2     count  15746.000000  15746.000000  15746.000000  15746.000000   
      mean      -0.159999     -0.081975      1.168139     -0.089649   
      std        0.695385      0.544348      0.534297      0.530898   
      min       -3.162795     -0.701499      0.125990     -0.800448   
      25%       -0.604232     -0.559336      0.739686     -0.515492   
      50%       -0.118077     -0.203928      1.126786     -0.225676   
      75%        0.332211      0.222562      1.598860      0.229809   
      max        1.972270      2.212849      2.302250      2.809697   
3     count  24560.000000  24560.000000  24560.000000  24560.000000   
      mean      -0.264456     -0.153641     -0.697837     -0.152985   
      std        0.694993      0.503033      0.440911      0.505737   
      min       -3.141290     -0.701499     -1.323277     -0.800448   
      25%       -0.699546     -0.559336     -1.086060     -0.540028   
      50%       -0.197673     -0.275009     -0.763870     -0.297737   
      75%        0.238626      0.080399     -0.359066      0.104840   
      max        1.324435      2.283930      0.391531      3.270220   
4     count   5352.000000   5352.000000   5352.000000   5352.000000   
      mean       0.314746      2.495196      0.487619      2.436241   
      std        0.888506      1.477550      1.001604      1.590578   
      min       -1.838692     -0.417173     -1.319737      0.023976   
      25%       -0.202694      1.573114     -0.392111      1.460442   
      50%        0.146586      2.141767      0.484176      2.000423   
      75%        0.546553      3.065828      1.356922      2.931497   
      max        4.034653     14.296729      2.302250     26.849457   

                       ZR  
Class                      
0     count   4712.000000  
      mean       0.019621  
      std        0.815459  
      min       -0.950023  
      25%       -0.679763  
      50%       -0.135166  
      75%        0.494990  
      max        2.944993  
1     count  12363.000000  
      mean       1.673645  
      std        0.646703  
      min        0.391775  
      25%        1.119714  
      50%        1.652087  
      75%        2.189892  
      max        3.015614  
2     count  15746.000000  
      mean      -0.381871  
      std        0.532442  
      min       -0.950023  
      25%       -0.819646  
      50%       -0.537163  
      75%       -0.097140  
      max        1.950868  
3     count  24560.000000  
      mean      -0.425707  
      std        0.443279  
      min       -0.950023  
      25%       -0.808782  
      50%       -0.542595  
      75%       -0.113437  
      max        1.244658  
4     count   5352.000000  
      mean      -0.806318  
      std        0.229348  
    