In [1]:
from __future__ import division
import os,sys

In [2]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [3]:
np.random.seed(12345)

In [4]:
np.set_printoptions(precision=4)
plt.rc('figure',figsize=(10,6))
br='\n'

NameError: name 'plt' is not defined

In [7]:
import matplotlib.pyplot as plt

In [8]:
np.set_printoptions(precision=4)
plt.rc('figure',figsize=(10,6))
br='\n'

In [9]:
s=Series([4,7,-5,3])
s

0    4
1    7
2   -5
3    3
dtype: int64

In [10]:
s=Series([4,7,-5,3]),index=['1','2','3','4']
s

SyntaxError: can't assign to function call (<ipython-input-10-cfa11416aba5>, line 1)

In [11]:
s=Series([4,7,-5,3],index=['1','2','3','4'])
s

1    4
2    7
3   -5
4    3
dtype: int64

In [12]:
print s.values,br
print s.index,br

[ 4  7 -5  3] 

Index([u'1', u'2', u'3', u'4'], dtype='object') 



In [1]:
1+2

3

In [4]:
from __future__ import division
import os,sys
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
br='\n'
s=Series([4,7,-5,3],index=['a','b','c','d'])
s
print s.index,br
print s.values,br

 Index([u'a', u'b', u'c', u'd'], dtype='object') 

[ 4  7 -5  3] 



In [5]:
print s['a'],br
s['a']=1
s

4 



a    1
b    7
c   -5
d    3
dtype: int64

In [6]:
pip install pandas_datareader

SyntaxError: invalid syntax (<ipython-input-6-16663e45080a>, line 1)

In [7]:
install pandas_datareader

SyntaxError: invalid syntax (<ipython-input-7-f92168bc31c4>, line 1)

In [8]:
from pandas_datareader import data
stock=data.get_data_yahoo('AAPL')

In [9]:
stock.head()

Open        High         Low       Close     Volume  \
Date                                                                    
2010-01-04  213.429998  214.499996  212.380001  214.009998  123432400   
2010-01-05  214.599998  215.589994  213.249994  214.379993  150476200   
2010-01-06  214.379993  215.230000  210.750004  210.969995  138040000   
2010-01-07  211.750000  212.000006  209.050005  210.580000  119282800   
2010-01-08  210.299994  212.000006  209.060005  211.980005  111902700   

            Adj Close  
Date                   
2010-01-04  27.727039  
2010-01-05  27.774976  
2010-01-06  27.333178  
2010-01-07  27.282650  
2010-01-08  27.464034

In [10]:
stock.tail()

Open        High         Low       Close    Volume  \
Date                                                                   
2017-03-03  138.779999  139.830002  138.589996  139.779999  21108100   
2017-03-06  139.369995  139.770004  138.600006  139.339996  21155300   
2017-03-07  139.059998  139.979996  138.789993  139.520004  17267500   
2017-03-08  138.949997  139.800003  138.820007  139.000000  18681800   
2017-03-09  138.740005  138.789993  137.050003  138.679993  22065200   

             Adj Close  
Date                    
2017-03-03  139.779999  
2017-03-06  139.339996  
2017-03-07  139.520004  
2017-03-08  139.000000  
2017-03-09  138.679993

In [11]:
sotck=data.get_data_yahoo('AAPL',start='1/1/2007')

In [12]:
sotck.head()

Open       High        Low      Close     Volume  Adj Close
Date                                                                        
2007-01-03  86.289999  86.579999  81.899999  83.800002  309579900  10.857091
2007-01-04  84.050001  85.949998  83.820003  85.659998  211815100  11.098071
2007-01-05  85.770000  86.199997  84.400002  85.049997  208685400  11.019039
2007-01-08  85.959998  86.529998  85.280003  85.470000  199276700  11.073455
2007-01-09  86.450003  92.979999  85.150000  92.570003  837324600  11.993328

In [15]:
s=Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
s=s.reindex(['a','b','c','d'])
print s

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64


In [16]:
s.reindex(['d','c','b','a'],fill_value=0)

d    4.5
c    3.6
b    7.2
a   -5.3
dtype: float64

In [17]:
print s

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64


In [18]:
s3=Series(['blue','purple','yellow'],index=[0,2,4])
s3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [21]:
frame=DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['O','T','C'])
frame

O  T  C
a  0  1  2
c  3  4  5
d  6  7  8

In [23]:
frame2=frame.reindex(['a','b','c','d'])
frame2

O    T    C
a  0.0  1.0  2.0
b  NaN  NaN  NaN
c  3.0  4.0  5.0
d  6.0  7.0  8.0

In [25]:
states=['T','U','C']
frame.reindex(columns=states)

T   U  C
a  1 NaN  2
c  4 NaN  5
d  7 NaN  8

In [27]:
frame.reindex(['a','b','c','d'],method='ffill',columns=states)

T   U  C
a  1 NaN  2
b  1 NaN  2
c  4 NaN  5
d  7 NaN  8

In [30]:
frame.ix[['a','b','c','d'],states]

T   U    C
a  1.0 NaN  2.0
b  NaN NaN  NaN
c  4.0 NaN  5.0
d  7.0 NaN  8.0

In [32]:
s=Series(np.arange(5.),index=['a','b','c','d','e'])
new_s=s.drop('c')
new_s

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [40]:
s.drop(['b','c'])
s

ValueError: labels ['b' 'c'] not contained in axis

In [42]:
data=DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [48]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [55]:
s=Series(np.arange(4.),index=['a','b','c','d'])
print s,br

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64 



In [56]:
print s['b']
print s[['b']]

1.0
b    1.0
dtype: float64


In [57]:
print s[1]

1.0


In [63]:
print s[2:4]
print s[['b','a','d']]
print s[[1,3]]
print s[s<2]
print s['b':'c']
s['b':'c']=5
print s['b':'c']

c    5.0
d    3.0
dtype: float64
b    5.0
a    0.0
d    3.0
dtype: float64
b    5.0
d    3.0
dtype: float64
a    0.0
dtype: float64
b    5.0
c    5.0
dtype: float64
b    5.0
c    5.0
dtype: float64


In [64]:
data=DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [66]:
print data['two']
print data.two
print data[['three','one']]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32
Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32
          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12


In [67]:
print data[0:1],br

      one  two  three  four
Ohio    0    1      2     3 



In [68]:
print data[:2],br

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7 



In [69]:
print data[1:2]

          one  two  three  four
Colorado    4    5      6     7


In [71]:
print data[3:4]

          one  two  three  four
New York   12   13     14    15


In [72]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [73]:
print data<5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False


In [74]:
data[data<5]=0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [76]:
data.ix['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [77]:
data.ix[['Ohio','Utah'],[3,0,1]]

four  one  two
Ohio     0    0    0
Utah    11    8    9

In [79]:
print data.ix[2]
print data.ix[2][1]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32
9


In [5]:
from __future__ import division
import os,sys
import numpy as np
import pandas as pd
from pandas_datareader import data
s1=Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2=Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g']);
s1+s2

NameError: name 'Series' is not defined

In [6]:
from __future__ import division
import os,sys
import numpy as np
import pandas as pd
from pandas_datareader import data

In [8]:
from pandas import Series,DataFrame
s1=Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2=Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g']);
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [10]:
list('bcd')
df1=DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),index=['Ohio','Texas','Colorado'])
df2=DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [11]:
arr=np.arange(12.).reshape((3,4))
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [12]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [13]:
arr-arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [14]:
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [15]:
frame=DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [16]:
series=frame.ix[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [17]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [18]:
series2=Series(range(3),index=['b','e','f'])
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [20]:
series3=frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [21]:
frame.sub(series3,axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [25]:
frame=DataFrame(np.random.randn(4,3),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah    0.643095  0.227522 -1.232917
Ohio   -0.398320  0.249542  0.242050
Texas   2.417544  1.174137  0.943012
Oregon -1.236846  0.722979 -0.150375

In [26]:
np.abs(frame)

b         d         e
Utah    0.643095  0.227522  1.232917
Ohio    0.398320  0.249542  0.242050
Texas   2.417544  1.174137  0.943012
Oregon  1.236846  0.722979  0.150375

In [27]:
f=lambda x:x.max()-x.min()

In [30]:
br='\n'
print frame,br
frame.apply(f)

               b         d         e
Utah    0.643095  0.227522 -1.232917
Ohio   -0.398320  0.249542  0.242050
Texas   2.417544  1.174137  0.943012
Oregon -1.236846  0.722979 -0.150375 



b    3.654390
d    0.946615
e    2.175929
dtype: float64

In [31]:
frame.apply(f,axis=1)

Utah      1.876013
Ohio      0.647862
Texas     1.474532
Oregon    1.959825
dtype: float64

In [33]:
def f(x):
    return Series([x.min(),x.max()],index=['min','max'])
frame.apply(f)

b         d         e
min -1.236846  0.227522 -1.232917
max  2.417544  1.174137  0.943012

In [34]:
format=lambda x: '%.2f' %x
frame.applymap(format)

b     d      e
Utah     0.64  0.23  -1.23
Ohio    -0.40  0.25   0.24
Texas    2.42  1.17   0.94
Oregon  -1.24  0.72  -0.15

In [35]:
frame['e'].map(format)

Utah      -1.23
Ohio       0.24
Texas      0.94
Oregon    -0.15
Name: e, dtype: object

In [38]:
s=Series(range(4),index=['d','a','b','c'])
print s,br
s.sort_index()

d    0
a    1
b    2
c    3
dtype: int64 



a    1
b    2
c    3
d    0
dtype: int64

In [40]:
frame=DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])
frame.sort_index()
frame.sort_index(axis=1)
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [41]:
s=Series([4,7,-3,2])
s.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [42]:
s=Series([7,-5,7,4,2,0,4])
s.rank()
s.rank(method='first')
s.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [47]:
frame=DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})
print frame,br
frame.rank()
frame.rank(axis=1)

   a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5 



a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

In [48]:
s=Series(range(5),index=['a','a','b','b','c'])

In [49]:
print s,br

a    0
a    1
b    2
b    3
c    4
dtype: int64 



In [50]:
s.index.is_unique

False

In [51]:
print s['a'],type(s['a'])
print s['c'],type(s['c'])

a    0
a    1
dtype: int64 <class 'pandas.core.series.Series'>
4 <type 'numpy.int64'>


In [53]:
df=DataFrame(np.random.randn(4,3),index=['a','a','b','c'])
print df,br
print df.ix['a'],type(df.ix['a'])
print df.ix['c'],type(df.ix['c'])

          0         1         2
a -0.610317 -1.576477 -0.551455
a  0.098304 -1.469985  0.996640
b  1.114361  0.398749  1.114910
c -0.518458 -1.073285 -1.607640 

          0         1         2
a -0.610317 -1.576477 -0.551455
a  0.098304 -1.469985  0.996640 <class 'pandas.core.frame.DataFrame'>
0   -0.518458
1   -1.073285
2   -1.607640
Name: c, dtype: float64 <class 'pandas.core.series.Series'>


In [55]:
df=DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=['a','b','c','d'],columns=['ones','two'])
df

ones  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [56]:
df.sum()

ones    9.25
two    -5.80
dtype: float64

In [57]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [58]:
df.mean(axis=1,skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [59]:
df.idxmax()

ones    b
two     d
dtype: object

In [60]:
df.cumsum()

ones  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [61]:
print type(df.describe()),br
df.describe()

<class 'pandas.core.frame.DataFrame'> 



ones       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [62]:
obj=Series(['a','a','b','c']*4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [63]:
obj=Series(['c','a','d','a','a','b','b','c','c'])

In [65]:
uniques=obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [66]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [67]:
pd.value_counts(obj.values,sort=False)

a    3
c    3
b    2
d    1
dtype: int64

In [68]:
mask=obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [69]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [70]:
data=DataFrame({'Qu1':[1,3,4,3,4],
               'Qu2':[2,3,1,2,3],
               'Qu3':[1,5,2,4,4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [71]:
data.Qu1.value_counts()

4    2
3    2
1    1
Name: Qu1, dtype: int64

In [72]:
string_data=Series(['aardvark','artichoke',np.nan,'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [73]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [75]:
string_data[0]=None
print string_data[0]
string_data.isnull()

None


0     True
1    False
2     True
3    False
dtype: bool

In [76]:
from numpy import nan as NA
data=Series([1,NA,3.5,NA,7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [77]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [80]:
data=DataFrame([[1.,6.5,3.],[1.,NA,NA],[NA,NA,NA],[NA,6.5,3.]])
cleaned=data.dropna()
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [81]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [82]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [83]:
data[4]=NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [84]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [85]:
df=DataFrame(np.random.randn(7,3))
df.ix[:4,1]=NA
df.ix[:2,2]=NA
df

0         1         2
0 -0.312952       NaN       NaN
1  0.269520       NaN       NaN
2 -1.762110       NaN       NaN
3 -1.700748       NaN  1.509876
4  1.522451       NaN -1.671305
5 -2.001218 -0.238332  1.921362
6 -0.857324 -0.277747 -0.124099

In [86]:
df.dropna(thresh=2)

0         1         2
3 -1.700748       NaN  1.509876
4  1.522451       NaN -1.671305
5 -2.001218 -0.238332  1.921362
6 -0.857324 -0.277747 -0.124099

In [87]:
print df,br

          0         1         2
0 -0.312952       NaN       NaN
1  0.269520       NaN       NaN
2 -1.762110       NaN       NaN
3 -1.700748       NaN  1.509876
4  1.522451       NaN -1.671305
5 -2.001218 -0.238332  1.921362
6 -0.857324 -0.277747 -0.124099 



In [88]:
df.fillna({1:0.5,2:-1})


0         1         2
0 -0.312952  0.500000 -1.000000
1  0.269520  0.500000 -1.000000
2 -1.762110  0.500000 -1.000000
3 -1.700748  0.500000  1.509876
4  1.522451  0.500000 -1.671305
5 -2.001218 -0.238332  1.921362
6 -0.857324 -0.277747 -0.124099

In [90]:
print df,br

          0         1         2
0 -0.312952       NaN       NaN
1  0.269520       NaN       NaN
2 -1.762110       NaN       NaN
3 -1.700748       NaN  1.509876
4  1.522451       NaN -1.671305
5 -2.001218 -0.238332  1.921362
6 -0.857324 -0.277747 -0.124099 



In [92]:
_=df.fillna(0,inplace=True)
df

0         1         2
0 -0.312952  0.000000  0.000000
1  0.269520  0.000000  0.000000
2 -1.762110  0.000000  0.000000
3 -1.700748  0.000000  1.509876
4  1.522451  0.000000 -1.671305
5 -2.001218 -0.238332  1.921362
6 -0.857324 -0.277747 -0.124099

In [93]:
df.fillna(method='ffill')

0         1         2
0 -0.312952  0.000000  0.000000
1  0.269520  0.000000  0.000000
2 -1.762110  0.000000  0.000000
3 -1.700748  0.000000  1.509876
4  1.522451  0.000000 -1.671305
5 -2.001218 -0.238332  1.921362
6 -0.857324 -0.277747 -0.124099

In [94]:
df.fillna(method='ffill',limit=2)

0         1         2
0 -0.312952  0.000000  0.000000
1  0.269520  0.000000  0.000000
2 -1.762110  0.000000  0.000000
3 -1.700748  0.000000  1.509876
4  1.522451  0.000000 -1.671305
5 -2.001218 -0.238332  1.921362
6 -0.857324 -0.277747 -0.124099

In [95]:
data=Series([1.,NA,3.5,NA,7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [96]:
data.fillna(data.median())

0    1.0
1    3.5
2    3.5
3    3.5
4    7.0
dtype: float64

In [97]:
np.random.randn(3)

array([-0.1974351 ,  1.77954325, -1.33392223])

In [99]:
data=Series(np.random.randn(10),index=[['a','a','a','b','b','b','c','c','d','d'],
                                      [1,2,3,1,2,3,1,2,2,3]])
data

a  1    0.241655
   2    0.295265
   3   -2.028979
b  1   -0.564464
   2   -0.010481
   3   -0.317260
c  1    0.100354
   2    0.444915
d  2    1.379962
   3   -0.980140
dtype: float64

In [100]:
data.index

MultiIndex(levels=[[u'a', u'b', u'c', u'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 1, 2]])

In [101]:
data['b']

1   -0.564464
2   -0.010481
3   -0.317260
dtype: float64

In [102]:
data['b':'c']

b  1   -0.564464
   2   -0.010481
   3   -0.317260
c  1    0.100354
   2    0.444915
dtype: float64

In [103]:
data.ix[['b','d']]

b  1   -0.564464
   2   -0.010481
   3   -0.317260
d  2    1.379962
   3   -0.980140
dtype: float64

In [104]:
data[:,2]

a    0.295265
b   -0.010481
c    0.444915
d    1.379962
dtype: float64

In [105]:
data.unstack()

1         2         3
a  0.241655  0.295265 -2.028979
b -0.564464 -0.010481 -0.317260
c  0.100354  0.444915       NaN
d       NaN  1.379962 -0.980140

In [106]:
data.unstack().stack()

a  1    0.241655
   2    0.295265
   3   -2.028979
b  1   -0.564464
   2   -0.010481
   3   -0.317260
c  1    0.100354
   2    0.444915
d  2    1.379962
   3   -0.980140
dtype: float64

In [107]:
frame=DataFrame(np.arange(12).reshape((4,3)),
               index=[['a','a','b','b'],[1,2,1,2]],
               columns=[['Ohio','Ohio','Colorado'],
                       ['Green','Red','Green']])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [108]:
frame.index

MultiIndex(levels=[[u'a', u'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [109]:
frame.index.names=['key1','key2']
frame.columns.names=['state','color']
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [110]:
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [111]:
print frame,br

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11 



In [113]:
frame.swaplevel('key1','key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [114]:
frame.sortlevel(1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [115]:
frame.swaplevel(0,1).sortlevel(0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [117]:
frame.swaplevel(0,1,axis=1).sortlevel(0,axis=0)

color     Green  Red    Green
state      Ohio Ohio Colorado
key1 key2                    
a    1        0    1        2
     2        3    4        5
b    1        6    7        8
     2        9   10       11

In [118]:
frame.sum(level='key2')

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16